### ISSUE TITLE
老大更新一下镜像。winit0.20.0用不了

### ISSUE THREAD

**Issue by Cupnfish** [rustcc/lernaean-deploy#5]

**Comment by DCjanus** [comment]
你是遇到了什么问题？是直接用目前我们部署的镜像无法连接还是自己部署的时候挂了？

如果是前者的话，那是因为目前部署的镜像被阿里云block了，暂时没有什么解决办法。
如果是后者的话，希望能够提供一下报错信息。

**Comment by Cupnfish** [comment]
额,前者...
